"""
color_correction.py
===================
Lighting / exposure correction via a printed color reference chart.

Method (after Bhadra et al., Lab Chip, 2012):
  - Place a card with N patches of *known* RGB values in every photo.
  - Measure the *observed* RGB of each patch from the captured image.
  - Fit an affine linear map  (3 × 4 matrix M) such that:

        M @ [R_obs, G_obs, B_obs, 1]ᵀ  ≈  [R_ref, G_ref, B_ref]ᵀ

    using least squares over all N patches.
  - Apply M to every pixel in the image before hue extraction.

This single step corrects for:
  - Overall exposure (brightness scaling)
  - White balance / ambient colour temperature
  - Channel-independent gain differences
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

import numpy as np


# ────────────────────────── reference patch definition ─────────────────────────

@dataclass
class RefPatch:
    """One colour patch on the reference card."""
    name: str
    known_rgb: tuple[int, int, int]   # ground-truth RGB (0-255) for this patch
    rect: tuple[int, int, int, int]   # (x, y, w, h) in the *original* image


# Patches matching reference_sticker.png (generated by generate_sticker.py).
# known_rgb = exact digital design values — the ground-truth the correction
# algorithm tries to map measured patch colours back to.
#
# rect (x, y, w, h) placeholders are (0,0,40,40) — located automatically
# from the detected sticker rect at runtime.
DEFAULT_PATCHES: list[RefPatch] = [
    # ── neutral ────────────────────────────────────────────────────────────
    # Known RGB = design values from generate_sticker.py (digital standard)
    RefPatch("White",        (235, 235, 235), (0, 0, 40, 40)),
    RefPatch("Mid Gray",     (128, 128, 128), (0, 0, 40, 40)),
    RefPatch("Black",        ( 25,  25,  25), (0, 0, 40, 40)),
    # ── chromatic (assay hue range 280-302 deg) ───────────────────────────
    RefPatch("Hue 302 low",  (209,  73, 205), (0, 0, 40, 40)),  # low  conc
    RefPatch("Hue 291 mid",  (189,  73, 209), (0, 0, 40, 40)),  # mid  conc
    RefPatch("Hue 280 high", (164,  73, 209), (0, 0, 40, 40)),  # high conc
]


# ────────────────────────── device geometry ────────────────────────────────────
#
# Physical dimensions of the SalivADetector device (mm).
# These match the printed sticker (reference_sticker.png) layout exactly.

WINDOW_W_MM      = 11.0   # sample window width
WINDOW_H_MM      =  5.3   # sample window height
GAP_MM           =  2.0   # vertical gap between window bottom and sticker top
STICKER_W_MM     = 11.0   # sticker width  (= window width, flush left)
STICKER_H_MM     = 11.0   # sticker height
STICKER_BORDER_MM =  0.4  # inner white margin of sticker
STICKER_DIVIDER_MM = 0.3  # gap between patches inside sticker
STICKER_ROWS     =  2
STICKER_COLS     =  3


def locate_sticker_patches(
    window_rect: tuple[int, int, int, int],             # (x, y, w, h) in pixels
    img_shape: tuple[int, int],                         # (img_h, img_w)
    sticker_rect: tuple[int, int, int, int] | None = None,  # override from blue-border detection
) -> list[tuple[int, int, int, int]]:
    """Compute the 6 sticker patch rects.

    If sticker_rect is provided (detected via blue border), its position
    and size are used directly.  Otherwise the location is derived
    geometrically from the window position and known physical dimensions.

    Returns a flat list of 6 (x, y, w, h) rects, row-major order:
        [White, MidGray, Black, Hue302, Hue291, Hue280]
    """
    img_h, img_w = img_shape

    if sticker_rect is not None:
        sx, sy, sw, sh = sticker_rect
        ppm = sw / STICKER_W_MM
    else:
        wx, wy, ww, wh = window_rect
        ppm = ww / WINDOW_W_MM                    # pixels per mm
        sx = wx
        sy = int(round(wy + wh + GAP_MM * ppm))
        sw = ww
        sh = int(round(STICKER_H_MM * ppm))

    border_px  = int(round(STICKER_BORDER_MM  * ppm))
    divider_px = int(round(STICKER_DIVIDER_MM * ppm))

    avail_w = sw - 2 * border_px - (STICKER_COLS - 1) * divider_px
    avail_h = sh - 2 * border_px - (STICKER_ROWS - 1) * divider_px
    pw = max(1, avail_w // STICKER_COLS)
    ph = max(1, avail_h // STICKER_ROWS)

    patches: list[tuple[int, int, int, int]] = []
    for r in range(STICKER_ROWS):
        for c in range(STICKER_COLS):
            px = sx + border_px + c * (pw + divider_px)
            py = sy + border_px + r * (ph + divider_px)
            # clamp to image bounds
            px = max(0, min(px, img_w - 1))
            py = max(0, min(py, img_h - 1))
            cw = min(pw, img_w - px)
            ch = min(ph, img_h - py)
            patches.append((px, py, cw, ch))

    return patches


# ────────────────────────── core math ──────────────────────────────────────────

def measure_patch(img_bgr: np.ndarray, rect: tuple[int, int, int, int]) -> np.ndarray:
    """Return mean RGB (float32, shape (3,)) of a rectangular patch."""
    x, y, w, h = rect
    x, y = max(0, x), max(0, y)
    roi = img_bgr[y: y + h, x: x + w]
    if roi.size == 0:
        raise ValueError(f"Patch rect {rect} is empty or outside the image.")
    mean_bgr = roi.reshape(-1, 3).mean(axis=0)
    return mean_bgr[::-1].astype(np.float32)   # → RGB


def compute_correction_matrix(
    observed_rgb: Sequence[np.ndarray],   # list of (3,) arrays, one per patch
    reference_rgb: Sequence[tuple[int, int, int]],
) -> np.ndarray:
    """
    Fit affine map M (3×4) such that:
        M @ [R_obs, G_obs, B_obs, 1]ᵀ  ≈  [R_ref, G_ref, B_ref]ᵀ

    Uses least squares; requires at least 1 patch, stable with ≥ 4.

    Returns
    -------
    M : np.ndarray, shape (3, 4), dtype float32
    residual_rgb : float   — mean per-channel absolute error on the patches
    """
    n = len(observed_rgb)
    if n == 0:
        raise ValueError("Need at least one reference patch.")

    # Build X (N×4) and Y (N×3)
    X = np.hstack([
        np.array(observed_rgb, dtype=np.float32),          # (N, 3)
        np.ones((n, 1), dtype=np.float32),                 # (N, 1)
    ])                                                      # (N, 4)
    Y = np.array(reference_rgb, dtype=np.float32)          # (N, 3)

    # Solve Y ≈ X @ M_T  →  M_T is (4, 3)
    M_T, _, _, _ = np.linalg.lstsq(X, Y, rcond=None)
    M = M_T.T                                              # (3, 4)

    # Compute residual
    predicted = X @ M_T                                    # (N, 3)
    residual_rgb = float(np.abs(predicted - Y).mean())

    return M.astype(np.float32), residual_rgb


def apply_correction(img_bgr: np.ndarray, M: np.ndarray) -> np.ndarray:
    """
    Apply a (3×4) affine correction matrix to every pixel of a BGR image.
    Pixels are clipped to [0, 255] after mapping.
    """
    img_rgb = img_bgr[:, :, ::-1].astype(np.float32)      # BGR → RGB float
    h, w = img_rgb.shape[:2]

    # Homogeneous: (H, W, 4) = [R, G, B, 1]
    ones = np.ones((h, w, 1), dtype=np.float32)
    homo = np.concatenate([img_rgb, ones], axis=2)         # (H, W, 4)

    corrected_rgb = homo @ M.T                             # (H, W, 3)
    corrected_rgb = np.clip(corrected_rgb, 0, 255).astype(np.uint8)
    return corrected_rgb[:, :, ::-1]                       # RGB → BGR


# ────────────────────────── convenience ────────────────────────────────────────

def make_swatch(rgb: tuple[int, int, int], size: int = 36) -> np.ndarray:
    """Return a small (size×size×3) uint8 RGB image filled with the given colour."""
    return np.full((size, size, 3), rgb, dtype=np.uint8)


def delta_e_simple(rgb1: np.ndarray, rgb2: tuple[int, int, int]) -> float:
    """Euclidean distance in RGB space (rough perceptual proxy)."""
    return float(np.linalg.norm(rgb1.astype(float) - np.array(rgb2, dtype=float)))
